#!/bin/zsh

NC='\e[0m'
RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
ORANGE='\e[33m'

echo "${BLUE}"
echo "    ____  ____  ________ __ __________ ";
echo "   / __ \/ __ \/ ____/ //_// ____/ __ \\";
echo "  / / / / / / / /   / ,<  / __/ / /_/ /";
echo " / /_/ / /_/ / /___/ /| |/ /___/ _, _/ ";
echo "/_____/\____/\____/_/ |_/_____/_/ |_|  ";
echo "      / /_  ___  / /___  ___  _____    ";
echo "     / __ \/ _ \/ / __ \/ _ \/ ___/    ";
echo "    / / / /  __/ / /_/ /  __/ /        ";
echo "   /_/ /_/\___/_/ .___/\___/_/         ";
echo "               /_/                     ";
echo "                                usavoia";
echo "                                 lrocca";
echo "                                 mcossu";
echo "${NC}"

if [[ "$1" == "help" ]]
then
	echo "${ORANGE}dock${NC}\t\tMoves Container folder"
	echo "${ORANGE}clean${NC}\t\tRemoves all traces of Docker"
	echo "${ORANGE}kill${NC}\t\tKills Docker process forcibly"
	echo ""
	exit
fi

echo "${RED}Closing${NC}\t\tDocker"
killall Docker &> /dev/null

if [[ "$1" == "kill" ]]
then
	echo ""
	exit
fi

if [[ "$1" == "clean" ]]
then
	rm -rf ~/Library/Containers/com.docker.docker
	rm -rf ~/goinfre/.docker
	echo "${RED}Deleted${NC}\t\tContainers folder"
	echo ""
	exit
fi

if ! ls -a ~/goinfre/.docker/ &> grep -q containers
then
	mkdir ~/goinfre/.docker &> /dev/null
	mkdir ~/goinfre/.docker/containers &> /dev/null
	echo "${GREEN}Created${NC}\t\tnew folder for Containers"
fi

if ls -F ~/Library/Containers/ | grep -q com.docker.docker/
then
	cp -R ~/Library/Containers/com.docker.docker/ ~/goinfre/.docker/containers/ &> /dev/null
	echo "${ORANGE}Moved${NC}\t\toriginal folder to new"
fi

if ! ls -F ~/Library/Containers/ | grep -q com.docker.docker@
then
	rm -rf ~/Library/Containers/com.docker.docker
	ln -sf ~/goinfre/.docker/containers ~/Library/Containers/com.docker.docker
	echo "${GREEN}Created${NC}\t\tlink from orignal path to new folder"
fi

open -a Docker
echo "${GREEN}Opened${NC}\t\tDocker"
echo ""
